# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Map Icons Dialog
                                 A QGIS Plugin
 This plugin provides a wide range of map icons with metadata display
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-25
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Syracuse University
        email                : bdasari@syr.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import re
import csv
import logging
from pathlib import Path

from qgis.PyQt import uic, QtWidgets, QtGui
from qgis.PyQt.QtCore import Qt, QSize, QTimer, QEvent, QByteArray
from qgis.PyQt.QtWidgets import (
    QLabel,
    QGridLayout,
    QMessageBox,
    QFormLayout,
    QSizePolicy,
    QSpacerItem,
)
from qgis.PyQt.QtSvg import QSvgRenderer

# Add the plugin directory to Python path for resources_rc import
import sys
plugin_dir = os.path.dirname(__file__)
if plugin_dir not in sys.path:
    sys.path.insert(0, plugin_dir)

# Import local modules
from .config import (
    MAX_ICONS_PER_ROW, 
    ICON_SIZE, 
    BUTTON_SIZE, 
    LABEL_MAX_WIDTH, 
    LABEL_MIN_HEIGHT,
    ICON_CARD_MIN_WIDTH,
    LABEL_STYLE,
    ICON_BUTTON_STYLE,
    CONTAINER_STYLE,
    METADATA_CSV_HEADERS,
    PLUGIN_ICON_FILENAME,
    METADATA_PREVIEW_SIZE,
    METADATA_PREVIEW_HEIGHT,
    DIALOG_STYLE,
    HEADER_STYLE,
    SEARCH_STYLE,
    SCROLL_AREA_STYLE,
    METADATA_PANEL_STYLE,
    METADATA_CLOSE_BUTTON_STYLE,
    PREVIEW_LABEL_STYLE,
    METADATA_GROUP_STYLE,
    FORMAT_GROUP_STYLE,
    METADATA_FIELD_LABEL_STYLE,
    METADATA_VALUE_STYLE,
    PRIMARY_TAG_VALUE_STYLE,
    SPLITTER_STYLE,
    BUTTON_BOX_STYLE,
)
from .data_manager import DataManager


def _normalize_svg_markup(svg_text):
    """
    This function rewrites SVG text so Qt can draw it in the preview.

    Latest SVGs from Zenodo comment out <style> and use stroke="param(outline), #000",
    which Qt doesnt understand and subsequently QSvgRenderer leaves blank in the preview panel.
    """
    text = re.sub(
        r"<!--\s*(<style\b.*?</style>)\s*-->",
        r"\1",
        svg_text,
        flags=re.DOTALL | re.IGNORECASE,
    )
    # param(name), fallback   or   param(name) fallback
    text = re.sub(r"param\([^)]+\),\s*", "", text)
    text = re.sub(r"param\([^)]+\)\s+", "", text)
    return text


# Metadata panel value labels that may wrap to multiple lines

METADATA_WRAP_ROWS = (
    ("secondaryTagsLabel", "secondaryTagsValue"),
    ("iconGeographyLabel", "iconGeographyValue"),
    ("iconDescriptionLabel", "iconDescriptionValue"),
    ("iconContextLabel", "iconContextValue"),
    ("creationContextLabel", "creationContextValue"),
    ("notesLabel", "notesValue"),
)

METADATA_ALL_VALUE_LABELS = (
    "codeValue",
    "createdByValue",
    "createdValue",
    "modifiedByValue",
    "modifiedValue",
    "whenUploadedValue",
    "secondaryTagsValue",
    "iconGeographyValue",
    "iconDescriptionValue",
    "iconContextValue",
    "creationContextValue",
    "notesValue",
)

METADATA_FIELD_LABELS = (
    "codeLabel",
    "createdByLabel",
    "createdLabel",
    "modifiedByLabel",
    "modifiedLabel",
    "whenUploadedLabel",
    "secondaryTagsLabel",
    "iconGeographyLabel",
    "iconDescriptionLabel",
    "iconContextLabel",
    "creationContextLabel",
    "notesLabel",
)

# Load the UI definition file
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'map_icons_dialog_base.ui'))


class mapIconsDialog(QtWidgets.QDialog, FORM_CLASS):
    """
    Main dialog class for the Map Icons plugin.
    
    This dialog displays a grid of map icons with their primary tags as labels.
    Icons with primary tags are displayed first, followed by icons without labels.
    Users can select icons to view detailed metadata in the right panel.
    """
    
    def __init__(self, parent=None):
        """Initialize the dialog and load icons with metadata."""
        super(mapIconsDialog, self).__init__(parent)
        
        # Set up the UI
        self.setupUi(self)
        self._plugin_icon_path = os.path.join(plugin_dir, PLUGIN_ICON_FILENAME)
        self._apply_dialog_theme()
        self._configure_metadata_form()
        
        # Initialize instance variables
        self.selected_icon = None       # Store the currently selected icon path
        self.selected_icon_png = None   # Store PNG version of selected icon
        self.selected_icon_svg = None   # Store SVG version of selected icon
        self.use_svg_format = False     # Flag to track if SVG format is selected
        self.selected_icon_filename = None  # Store filename for SVG lookup
        self.icon_buttons = []          # Keep references to buttons for highlighting
        self.icon_metadata = {}         # Store comprehensive metadata for each icon (indexed by filename)
        self.metadata_list = []         # Store metadata in order to match with sorted icon files
        self.data_manager = None        # Data manager for Zenodo downloads
        self.actual_icons_dir = None    # Store where icons were actually found
        self.icon_entries = []          # Store per-icon data for search/filtering
        self._icons_loaded = False
        self._grid_columns = MAX_ICONS_PER_ROW
        
        # Branded header and search above the icon grid
        self.headerWidget = QtWidgets.QWidget(self)
        header_layout = QtWidgets.QHBoxLayout(self.headerWidget)
        header_layout.setContentsMargins(0, 0, 0, 0)
        header_layout.setSpacing(12)

        self.headerIconLabel = QtWidgets.QLabel(self.headerWidget)
        self.headerIconLabel.setFixedSize(36, 36)
        self.headerIconLabel.setScaledContents(True)
        if os.path.isfile(self._plugin_icon_path):
            self.headerIconLabel.setPixmap(
                QtGui.QPixmap(self._plugin_icon_path).scaled(
                    36, 36, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation
                )
            )

        self.dialogHeaderLabel = QtWidgets.QLabel("Map Icons", self.headerWidget)
        self.dialogHeaderLabel.setObjectName("dialogHeaderLabel")
        self.dialogHeaderLabel.setStyleSheet(HEADER_STYLE)

        header_layout.addWidget(self.headerIconLabel)
        header_layout.addWidget(self.dialogHeaderLabel)
        header_layout.addStretch()

        self.searchLineEdit = QtWidgets.QLineEdit(self)
        self.searchLineEdit.setPlaceholderText(
            "Search icons by tags, geography, or designer..."
        )
        self.searchLineEdit.setClearButtonEnabled(True)
        self.searchLineEdit.setStyleSheet(SEARCH_STYLE)
        self.searchLineEdit.setMinimumHeight(38)
        self.searchLineEdit.textChanged.connect(self.on_search_text_changed)
        if hasattr(self, 'mainLayout'):
            self.mainLayout.insertWidget(0, self.headerWidget)
            self.mainLayout.insertWidget(1, self.searchLineEdit)
            self.mainLayout.setSpacing(6)
            self.mainLayout.setContentsMargins(12, 8, 12, 10)
            splitter_idx = self.mainLayout.indexOf(self.splitter)
            if splitter_idx >= 0:
                self.mainLayout.setStretch(splitter_idx, 1)
            self.mainLayout.setStretch(0, 0)
            self.mainLayout.setStretch(1, 0)
        

        # Ensure metadata panel is hidden by default
        self.metadataPanel.setVisible(False)
        
        # Ensure format group is visible by default (will be shown when icon is selected)
        if hasattr(self, 'formatGroup'):
            self.formatGroup.setVisible(True)
        
        # Connect Cancel button to clear selection
        self.button_box.rejected.connect(self.on_cancel_clicked)
        if hasattr(self, "metadataCloseButton"):
            self.metadataCloseButton.clicked.connect(self.on_cancel_clicked)
        
        # Connect format radio buttons if they exist
        if hasattr(self, 'pngFormatRadio') and hasattr(self, 'svgFormatRadio'):
            self.pngFormatRadio.setAutoExclusive(True)
            self.svgFormatRadio.setAutoExclusive(True)
            self.pngFormatRadio.clicked.connect(self.on_format_changed)
            self.svgFormatRadio.clicked.connect(self.on_format_changed)
            self.pngFormatRadio.toggled.connect(self.on_format_changed)
            self.svgFormatRadio.toggled.connect(self.on_format_changed)
            self.pngFormatRadio.setEnabled(True)
            self.pngFormatRadio.setChecked(True)
            self.svgFormatRadio.setEnabled(False)  # Will be enabled when SVG is available
            self.svgFormatRadio.setVisible(True)
        
        # Initialize data manager and ensure data is available
        self.initialize_data()
        
        # Load metadata and icons
        if self.data_manager:
            print("=== LOADING METADATA ===")
            self.load_metadata()
            print(f"Metadata list length: {len(self.metadata_list) if hasattr(self, 'metadata_list') else 0}")
            
            print("=== LOADING ICONS ===")
            self.load_icons()
            print(f"Icon buttons created: {len(self.icon_buttons)}")
        else:
            print("ERROR: data_manager is None!")
            self.show_error_message("Failed to initialize data manager")
    
    def initialize_data(self):
        """Initialize data manager and ensure required data is available."""
        try:
            print("=== INITIALIZING DATA MANAGER ===")
            self.data_manager = DataManager(os.path.dirname(__file__))
            print(f"Data manager created. Cache dir: {self.data_manager.cache_dir}")
            print(f"Icons cache dir: {self.data_manager.icons_cache_dir}")
            
            # Show progress dialog for data download
            progress_dialog = QtWidgets.QProgressDialog(
                "Checking and downloading required data...", 
                "Cancel", 
                0, 
                0, 
                self
            )
            progress_dialog.setWindowTitle("Map Icons Plugin")
            progress_dialog.setModal(True)
            progress_dialog.show()
            
            # Ensure data is available
            print("Calling ensure_data_available()...")
            if not self.data_manager.ensure_data_available():
                progress_dialog.close()
                error_msg = (
                    "Failed to download required data from Zenodo.\n\n"
                    "Please check:\n"
                    "1. Your internet connection\n"
                    "2. QGIS Log Messages for details\n"
                    "3. Python Console for error messages"
                )
                print("ERROR: ensure_data_available() returned False")
                self.show_error_message(error_msg)
                return
            
            progress_dialog.close()
            print("✓ Data manager initialized successfully")
            
        except Exception as e:
            import traceback
            error_details = traceback.format_exc()
            print(f"EXCEPTION in initialize_data: {e}")
            print(error_details)
            logging.error(f"Failed to initialize data manager: {e}")
            logging.error(error_details)
            self.show_error_message(f"Failed to initialize data manager: {e}\n\nCheck Python Console for details.")
    
    def show_error_message(self, message):
        """Show an error message to the user."""
        QMessageBox.critical(self, "Error", message)

    def on_cancel_clicked(self):
        """Handle Cancel button click - hide metadata panel and clear selection."""
        self.clear_selection()

    def _apply_dialog_theme(self):
        """Apply colour palette and styles to the dialog."""
        self.setStyleSheet(DIALOG_STYLE)
        self.setMinimumSize(920, 640)

        if os.path.isfile(self._plugin_icon_path):
            self.setWindowIcon(QtGui.QIcon(self._plugin_icon_path))

        if hasattr(self, "scrollArea"):
            self.scrollArea.setStyleSheet(SCROLL_AREA_STYLE)
        if hasattr(self, "scrollAreaWidgetContents"):
            self.scrollAreaWidgetContents.setStyleSheet("background: transparent;")
            self.scrollAreaWidgetContents.setSizePolicy(
                QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum
            )
        if hasattr(self, "metadataPanel"):
            self.metadataPanel.setStyleSheet(METADATA_PANEL_STYLE)
        if hasattr(self, "metadataCloseButton"):
            self.metadataCloseButton.setObjectName("metadataCloseButton")
            self.metadataCloseButton.setStyleSheet(METADATA_CLOSE_BUTTON_STYLE)
            self.metadataCloseButton.setCursor(Qt.CursorShape.PointingHandCursor)
        if hasattr(self, "iconPreviewLabel"):
            self.iconPreviewLabel.setStyleSheet(PREVIEW_LABEL_STYLE)
            self.iconPreviewLabel.setFixedHeight(METADATA_PREVIEW_HEIGHT)
            self.iconPreviewLabel.setMaximumHeight(METADATA_PREVIEW_HEIGHT)
            self.iconPreviewLabel.setSizePolicy(
                QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed
            )
            self.iconPreviewLabel.setScaledContents(False)
        if hasattr(self, "metadataGroup"):
            self.metadataGroup.setStyleSheet(METADATA_GROUP_STYLE)
        if hasattr(self, "formatGroup"):
            self.formatGroup.setStyleSheet(FORMAT_GROUP_STYLE)
        if hasattr(self, "metadataScrollArea"):
            self.metadataScrollArea.setStyleSheet(SCROLL_AREA_STYLE)
        if hasattr(self, "metadataScrollContents"):
            self.metadataScrollContents.setStyleSheet("background: transparent;")
        if hasattr(self, "button_box"):
            self.button_box.setStyleSheet(BUTTON_BOX_STYLE)
        if hasattr(self, "splitter"):
            self.splitter.setStyleSheet(SPLITTER_STYLE)
            self.splitter.setHandleWidth(6)
        if hasattr(self, "metadataLayout"):
            self.metadataLayout.setContentsMargins(12, 10, 12, 10)
            self.metadataLayout.setSpacing(8)
            preview_idx = self.metadataLayout.indexOf(self.iconPreviewLabel)
            scroll_idx = self.metadataLayout.indexOf(self.metadataScrollArea)
            format_idx = (
                self.metadataLayout.indexOf(self.formatGroup)
                if hasattr(self, "formatGroup")
                else -1
            )
            if preview_idx >= 0:
                self.metadataLayout.setStretch(preview_idx, 0)
            if scroll_idx >= 0:
                self.metadataLayout.setStretch(scroll_idx, 1)
            if format_idx >= 0:
                self.metadataLayout.setStretch(format_idx, 0)
        if hasattr(self, "iconLayout"):
            self.iconLayout.setAlignment(Qt.AlignmentFlag.AlignCenter | Qt.AlignmentFlag.AlignTop)
            self.iconLayout.setSpacing(24)
            self.iconLayout.setContentsMargins(16,8,16,16)
        if hasattr(self, "splitter"):
            self.splitter.splitterMoved.connect(
                lambda *_args: self._schedule_icon_grid_relayout()
            )
        if hasattr(self, "scrollArea"):
            viewport = self.scrollArea.viewport()
            if viewport is not None:
                viewport.installEventFilter(self)

    def showEvent(self, event):
        """Reflow icon grid once the dialog has a real width."""
        super(mapIconsDialog, self).showEvent(event)
        if self._icons_loaded:
            self._schedule_icon_grid_relayout(force=True)

    def _icon_grid_column_count(self):
        """How many icon cards fit in the current scroll area width."""
        if not hasattr(self, "scrollArea"):
            return MAX_ICONS_PER_ROW
        viewport = self.scrollArea.viewport()
        if viewport is None or viewport.width() < ICON_CARD_MIN_WIDTH:
            return getattr(self, "_grid_columns", MAX_ICONS_PER_ROW)

        layout = self.iconLayout
        margins = layout.contentsMargins()
        spacing = layout.spacing() or 12
        available = viewport.width() - margins.left() - margins.right()
        if available < ICON_CARD_MIN_WIDTH:
            return 1

        columns = int((available + spacing) // (ICON_CARD_MIN_WIDTH + spacing))
        return max(1, min(columns, MAX_ICONS_PER_ROW))

    def _relayout_icon_grid(self, force=False):
        """Reposition icon cards when the left pane grows or shrinks."""
        if not self._icons_loaded or not self.icon_entries:
            return

        viewport = (
            self.scrollArea.viewport() if hasattr(self, "scrollArea") else None
        )
        if viewport is not None and viewport.width() < ICON_CARD_MIN_WIDTH:
            return

        new_columns = self._icon_grid_column_count()
        if not force and new_columns == self._grid_columns:
            return

        self._grid_columns = new_columns
        layout = self.iconLayout
        parent = (
            self.scrollAreaWidgetContents
            if hasattr(self, "scrollAreaWidgetContents")
            else None
        )

        ordered = []
        for entry in self.icon_entries:
            container = entry.get("container")
            if container is not None:
                ordered.append((container, container.isVisible()))

        for index in reversed(range(layout.count())):
            item = layout.itemAt(index)
            widget = item.widget() if item else None
            if widget is not None:
                layout.removeWidget(widget)

        row = 0
        col = 0
        for container, visible in ordered:
            if parent is not None:
                container.setParent(parent)
            if not visible:
                container.hide()
                continue
            layout.addWidget(container, row, col, Qt.AlignmentFlag.AlignCenter)
            container.show()
            col += 1
            if col >= new_columns:
                col = 0
                row += 1

        if parent is not None:
            parent.updateGeometry()

    def _schedule_icon_grid_relayout(self, force=False):
        QTimer.singleShot(0, lambda: self._relayout_icon_grid(force=force))

    def _configure_metadata_form(self):
        """Top-align rows, span values full width, and keep row spacing even."""
        if not hasattr(self, "metadataForm"):
            return
        align = Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop
        self.metadataForm.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.metadataForm.setLabelAlignment(align)
        self.metadataForm.setFormAlignment(align)
        self.metadataForm.setVerticalSpacing(6)
        self.metadataForm.setHorizontalSpacing(10)
        for label_name, value_name in METADATA_WRAP_ROWS:
            if hasattr(self, label_name) and hasattr(self, value_name):
                label = getattr(self, label_name)
                value = getattr(self, value_name)
                label.setAlignment(align)
                value.setWordWrap(True)
                value.setAlignment(align)
                self.metadataForm.setAlignment(label, align)
                self.metadataForm.setAlignment(value, align)
        for name in METADATA_ALL_VALUE_LABELS:
            if hasattr(self, name):
                label = getattr(self, name)
                label.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
                label.setStyleSheet(METADATA_VALUE_STYLE)
        for name in METADATA_FIELD_LABELS:
            if hasattr(self, name):
                getattr(self, name).setStyleSheet(METADATA_FIELD_LABEL_STYLE)
        if hasattr(self, "metadataGroup"):
            self.metadataGroup.setSizePolicy(
                QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred
            )
        if hasattr(self, "metadataScrollContents"):
            self.metadataScrollContents.setSizePolicy(
                QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred
            )
        if hasattr(self, "metadataScrollArea"):
            self.metadataScrollArea.setWidgetResizable(True)
            viewport = self.metadataScrollArea.viewport()
            if viewport is not None:
                viewport.installEventFilter(self)
        if not getattr(self, "_metadata_form_spacer_added", False):
            self.metadataForm.addItem(
                QSpacerItem(0, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
            )
            self._metadata_form_spacer_added = True
        if hasattr(self, "metadataLayout") and hasattr(self, "metadataScrollArea"):
            idx = self.metadataLayout.indexOf(self.metadataScrollArea)
            if idx >= 0:
                self.metadataLayout.setStretch(idx, 1)

    def eventFilter(self, obj, event):
        """Recalculate layouts when scroll areas are resized."""
        if event.type() == QEvent.Type.Resize:
            if (
                hasattr(self, "metadataScrollArea")
                and obj is self.metadataScrollArea.viewport()
            ):
                QTimer.singleShot(0, self._sync_metadata_layout)
            elif (
                hasattr(self, "scrollArea")
                and obj is self.scrollArea.viewport()
            ):
                self._schedule_icon_grid_relayout()
        return super(mapIconsDialog, self).eventFilter(obj, event)

    def _metadata_field_column_width(self, panel_width):
        """Shared width for every value column cell in the metadata form."""
        return max(panel_width - 135, 180)

    def _sync_metadata_layout(self):
        """Keep all value labels full-width with even row spacing."""
        if not hasattr(self, "metadataScrollArea"):
            return
        viewport = self.metadataScrollArea.viewport()
        if viewport is None or viewport.width() <= 1:
            return
        panel_width = viewport.width()
        field_width = self._metadata_field_column_width(panel_width)
        if hasattr(self, "metadataScrollContents"):
            self.metadataScrollContents.setMinimumWidth(panel_width)
        if hasattr(self, "metadataGroup"):
            self.metadataGroup.setMinimumWidth(panel_width)
        self.metadataForm.update()
        for name in METADATA_ALL_VALUE_LABELS:
            if not hasattr(self, name):
                continue
            label = getattr(self, name)
            label.setWordWrap(True)
            label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
            label.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
            label.setMinimumWidth(field_width)
            text = (label.text() or "").strip()
            if text and text != "-":
                label.setMinimumHeight(label.heightForWidth(field_width))
            else:
                label.setMinimumHeight(0)
        if hasattr(self, "metadataScrollContents"):
            self.metadataScrollContents.updateGeometry()

    def _set_label(self, widget_name, value):
        if not hasattr(self, widget_name):
            return
        label = getattr(self, widget_name)
        text = value if value else "-"
        if widget_name in METADATA_ALL_VALUE_LABELS:
            label.setWordWrap(True)
            label.setAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignTop)
        label.setText(text)

    def _reset_metadata_label_heights(self):
        """Clear stale minimum sizes before showing a new icon."""
        for name in METADATA_ALL_VALUE_LABELS:
            if hasattr(self, name):
                widget = getattr(self, name)
                widget.setMinimumHeight(0)
                widget.setMinimumWidth(0)

    @staticmethod
    def _metadata_header_indices(headers):
        """
        Map each expected CSV header to its column index.
        Returns (indices dict, list of missing headers).
        """
        lookup = {h.strip(): i for i, h in enumerate(headers)}
        indices = {}
        missing = []
        for name in METADATA_CSV_HEADERS:
            if name not in lookup:
                missing.append(name)
            else:
                indices[name] = lookup[name]
        return indices, missing

    def _ingest_metadata_rows(self, headers, rows_of_strings):
        """Populate metadata_list / metadata_by_filename from CSV rows."""
        col, missing = self._metadata_header_indices(headers)
        if missing:
            logging.error("Metadata file missing columns: %s", missing)
            self.metadata_list = []
            self.metadata_by_filename = {}
            self.icon_metadata = {}
            self.show_error_message(
                "Metadata file is missing required columns:\n" + ", ".join(missing)
            )
            return

        metadata_list = []
        metadata_by_filename = {}

        for row in rows_of_strings:
            cells = list(row)
            while len(cells) < len(headers):
                cells.append("")

            def cell(header):
                i = col[header]
                return str(cells[i]).strip() if i < len(cells) and cells[i] else ""

            uid = cell("unique-ID")
            filename = None
            if uid:
                filename = Path(uid).name
                if not filename.lower().endswith(".png"):
                    filename = f"{filename}.png"

            metadata = {
                "filename": filename,
                "designer": cell("designer"),
                "metadata_source": cell("metadata-source"),
                "uploader": cell("uploader"),
                "primary_tag": cell("primary-tags"),
                "secondary_tags": cell("secondary-tags"),
                "when_created": cell("when-created"),
                "when_uploaded": cell("when-uploaded"),
                "where_created": cell("where-created"),
                "icon_geography": cell("icon-geography"),
                "icon_description": cell("icon-description"),
                "icon_context": cell("icon-context"),
                "creation_context": cell("creation-context"),
                "notes": cell("notes"),
            }
            metadata_list.append(metadata)
            if filename:
                metadata_by_filename[filename] = metadata

        self.icon_metadata = {}
        self.metadata_list = metadata_list
        self.metadata_by_filename = metadata_by_filename
        logging.info(
            "Loaded %s metadata rows; %s keyed by unique-ID",
            len(metadata_list),
            len(metadata_by_filename),
        )

    def load_metadata(self):
        """Load icon metadata from the cached CSV downloaded from Zenodo."""
        if not self.data_manager:
            logging.error("Data manager not initialized")
            return

        logging.info("=== Loading metadata file ===")

        metadata_file = self.data_manager.get_metadata_file()
        logging.info(f"Metadata file path: {metadata_file}")
        logging.info(f"Metadata file exists: {metadata_file.exists()}")

        if not metadata_file.exists():
            logging.error(f"Metadata file not found: {metadata_file}")
            self.show_error_message("Metadata file not found. Please check data download.")
            return

        if metadata_file.suffix.lower() != ".csv":
            self.show_error_message(
                "Metadata must be a CSV file downloaded from Zenodo (map-icon-metadata.csv)."
            )
            return

        try:
            with open(metadata_file, newline="", encoding="utf-8-sig") as f:
                reader = csv.reader(f)
                all_rows = list(reader)
            if not all_rows:
                raise ValueError("Empty CSV")
            headers = [str(h).strip() if h else "" for h in all_rows[0]]
            rows_of_strings = []
            for raw in all_rows[1:]:
                vals = [str(c).strip() if c else "" for c in raw]
                if not any(vals):
                    continue
                rows_of_strings.append(vals)
            self._ingest_metadata_rows(headers, rows_of_strings)

        except Exception as e:
            logging.error(f"Error loading metadata file: {e}")
            import traceback
            traceback.print_exc()
            self.icon_metadata = {}
            self.metadata_list = []
            self.metadata_by_filename = {}
            self.show_error_message(f"Failed to load metadata: {e}")

    def load_icons(self):
        """
        Load and display all icons in a grid layout.
        
        Icons are organized as follows:
        1. Icons with primary tags are displayed first
        2. Icons without primary tags are displayed after
        3. Each icon with a label shows the icon above and label below
        4. Icons without labels show only the icon button
        """
        print("=== Loading icons into grid layout ===")
        
        # Get the grid layout from the UI
        layout: QGridLayout = self.iconLayout
        max_columns = self._icon_grid_column_count()
        self._grid_columns = max_columns
        
        # Get all icon files from the data manager
        if not self.data_manager:
            logging.error("Data manager not initialized")
            return
        
        icons_dir = self.data_manager.get_icons_directory()
        if not icons_dir.exists():
            logging.error(f"Icons directory not found: {icons_dir}")
            self.show_error_message("Icons directory not found. Please check data download.")
            return
        
        from .config import PNG_FOLDER

        possible_icon_dirs = []
        png_dir = self.data_manager.get_png_icons_directory()
        if png_dir is not None:
            possible_icon_dirs.append(png_dir)
        possible_icon_dirs.extend([
            self.data_manager.cache_dir / PNG_FOLDER,
            icons_dir,
        ])
        
        actual_icons_dir = None
        for possible_dir in possible_icon_dirs:
            if possible_dir.exists() and list(possible_dir.glob("*.png")):
                actual_icons_dir = possible_dir
                logging.info(f"Found icons in: {actual_icons_dir}")
                break
        
        # Store the actual icons directory for SVG lookup
        if actual_icons_dir:
            self.actual_icons_dir = actual_icons_dir
        
        if actual_icons_dir is None:
            # Try to find any PNG files recursively in the entire cache directory
            print(f"Searching recursively for PNG files in cache directory...")
            all_pngs = list(self.data_manager.cache_dir.rglob("*.png"))
            if all_pngs:
                actual_icons_dir = all_pngs[0].parent
                print(f"Found {len(all_pngs)} PNG files recursively in: {actual_icons_dir}")
                logging.info(f"Found icons recursively in: {actual_icons_dir}")
            else:
                # Also check for files without .png extension
                print(f"Checking for files without .png extension...")
                all_files = list(self.data_manager.cache_dir.rglob("*"))
                png_files_no_ext = []
                for f in all_files:
                    if f.is_file() and not f.name.startswith('._') and f.name != '.DS_Store':
                        try:
                            with open(f, 'rb') as check_file:
                                header = check_file.read(8)
                                if header[:8] == b'\x89PNG\r\n\x1a\n':
                                    png_files_no_ext.append(f)
                        except OSError:
                            continue
                    
                if png_files_no_ext:
                    actual_icons_dir = png_files_no_ext[0].parent
                    print(f"Found {len(png_files_no_ext)} PNG files (without extension) in: {actual_icons_dir}")
                    logging.info(f"Found PNG files without extension in: {actual_icons_dir}")
                else:
                    error_msg = (
                        f"No icon files found in cache directory.\n\n"
                        f"Searched in: {self.data_manager.cache_dir}\n\n"
                        f"Please check:\n"
                        f"1. Internet connection\n"
                        f"2. Zenodo download completed\n"
                        f"3. Check QGIS Log Messages for download errors"
                    )
                    print(f"ERROR: {error_msg}")
                    logging.error(f"No PNG files found in {icons_dir} or subdirectories")
                    self.show_error_message(error_msg)
                    return
        
        # Store the actual icons directory for later use
        self.actual_icons_dir = actual_icons_dir
        
        # Get all PNG files, including those without .png extension visible
        all_png_files = list(actual_icons_dir.glob("*.png"))
        # Also check for files without extension that might be PNGs
        all_files = list(actual_icons_dir.glob("*"))
        
        # Filter out macOS resource fork files (._*) and .DS_Store
        all_icon_files = []
        for f in all_files:
            name = f.name
            # Skip macOS resource forks and system files
            if name.startswith('._') or name == '.DS_Store':
                continue
            # Include files with .png extension or files that are actually PNGs
            if name.endswith('.png') or name.endswith('.PNG'):
                all_icon_files.append(name)
            elif f.is_file():
                # Check if file without extension is actually a PNG by checking magic bytes
                try:
                    with open(f, 'rb') as check_file:
                        header = check_file.read(8)
                        # PNG files start with: 89 50 4E 47 0D 0A 1A 0A
                        if header[:8] == b'\x89PNG\r\n\x1a\n':
                            all_icon_files.append(name)
                except OSError:
                    continue
        
        print(f"Found {len(all_icon_files)} PNG files in {actual_icons_dir}")
        logging.info(f"Found {len(all_icon_files)} PNG files in {actual_icons_dir}")
        if all_icon_files:
            print(f"Sample icon files: {all_icon_files[:10]}")
            logging.info(f"Sample icon files: {all_icon_files[:5]}")
        else:
            print(f"WARNING: No PNG files found in {actual_icons_dir}")
            self.show_error_message(f"No PNG icon files found in:\n{actual_icons_dir}\n\nPlease check if icons were downloaded correctly.")
        
        self.icon_metadata = {}
        icon_files = []

        # --- Zenodo v4+ / unique IDs: match by filename column in spreadsheet (same stem as .png on disk)
        if getattr(self, 'metadata_by_filename', None) and len(self.metadata_by_filename) > 0:
            disk_names = set(all_icon_files)
            lower_map = {n.lower(): n for n in disk_names}
            logging.info(
                f"Filename-based matching: {len(self.metadata_by_filename)} metadata filenames vs "
                f"{len(disk_names)} PNGs on disk"
            )
            for meta in self.metadata_list:
                fn = meta.get('filename')
                if not fn:
                    continue
                fn = Path(fn).name
                if fn not in disk_names:
                    fn = lower_map.get(fn.lower(), fn)
                if fn in disk_names:
                    icon_files.append(fn)
                    self.icon_metadata[fn] = meta
            if not icon_files:
                sample = ', '.join(list(disk_names)[:8])
                meta_sample = ', '.join(list(self.metadata_by_filename.keys())[:8])
                meta_keys = [k.strip() for k in meta_sample.split(",") if k.strip()]
                legacy_disk = bool(disk_names) and all(
                    re.fullmatch(r"\d+\.png", n, re.I) for n in disk_names
                )
                id_meta = bool(meta_keys) and re.fullmatch(
                    r"[a-f0-9]{4,}\.png", meta_keys[0], re.I
                )
                hint = ""
                if legacy_disk and id_meta:
                    hint = (
                        "\n\nYour cache still has OLD numbered icons (1.png, 2.png, …) from a "
                        "previous Zenodo version. Delete the plugin’s cache folder, then open "
                        "the plugin again so it can download the latest icons from Zenodo."
                    )
                self.show_error_message(
                    "No icons matched metadata filenames.\n\n"
                    "Check that the spreadsheet filename column exactly matches PNG names on disk "
                    "(e.g. 047678c6.png).\n\n"
                    f"Sample PNGs on disk: {sample}\n"
                    f"Sample metadata filenames: {meta_sample}"
                    f"{hint}"
                )
                return
            print(f"Matched {len(icon_files)} icons by filename to metadata rows")
            logging.info(f"Matched {len(icon_files)} icons by filename")
        else:
            self.show_error_message(
                "Metadata could not be loaded.\n\n"
                "The CSV must include these columns:\n"
                + ", ".join(METADATA_CSV_HEADERS)
            )
            return

        print(f"Total icons to display: {len(icon_files)}")

        # Separate icons into two categories: with labels and without labels
        icons_with_labels = []
        icons_without_labels = []
        
        # Process each icon file
        for icon_file in icon_files:
            # Get metadata for this icon
            if icon_file in self.icon_metadata:
                metadata = self.icon_metadata[icon_file]
                primary_tag = metadata.get("primary_tag", "")
                
                # Use primary_tag as the display name for the icon label
                display_name = primary_tag if primary_tag and primary_tag.strip() else None
            else:
                display_name = None
            
            # Categorize the icon
            if display_name:
                icons_with_labels.append((icon_file, display_name))
            else:
                icons_without_labels.append(icon_file)
        
        print(f"Icons with labels: {len(icons_with_labels)}")
        print(f"Icons without labels: {len(icons_without_labels)}")
        logging.info(f"Icons with labels: {len(icons_with_labels)}")
        logging.info(f"Icons without labels: {len(icons_without_labels)}")
        
        if len(icons_with_labels) == 0 and len(icons_without_labels) == 0:
            print("ERROR: No icons to display!")
            self.show_error_message("No icons found to display. Check Python Console for details.")
            return
        
        # Display icons in the grid layout
        row, col = 0, 0
        
        # First, display all icons with labels
        for icon_file, display_name in icons_with_labels:
            self._create_icon_widget(layout, icon_file, display_name, row, col)
            
            # Move to next position in grid
            col += 1
            if col >= max_columns:
                col = 0
                row += 1
        
        # Then, display all icons without labels
        for icon_file in icons_without_labels:
            self._create_icon_widget(layout, icon_file, None, row, col)
            
            # Move to next position in grid
            col += 1
            if col >= max_columns:
                col = 0
                row += 1

        self._icons_loaded = True
        self._schedule_icon_grid_relayout(force=True)

    def _create_icon_widget(self, layout, icon_file, display_name, row, col):
        """
        Create a widget containing an icon button and optionally a label.
        Enhanced with modern card-style design.
        
        Args:
            layout: The grid layout to add the widget to
            icon_file: The filename of the icon
            display_name: The display name to show as label (None if no label)
            row: Grid row position
            col: Grid column position
        """
        # Create container widget with vertical layout (card-style)
        container = QtWidgets.QWidget()
        container.setStyleSheet(CONTAINER_STYLE)
        container_layout = QtWidgets.QVBoxLayout(container)
        container_layout.setContentsMargins(6, 6, 6, 6)
        container_layout.setSpacing(6)
        container_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        
        # Create the icon button with enhanced styling
        btn = QtWidgets.QPushButton()
        # Use actual_icons_dir if we found it during loading, otherwise use default
        if hasattr(self, 'actual_icons_dir') and self.actual_icons_dir:
            icon_path = self.actual_icons_dir / icon_file
        else:
            icon_path = self.data_manager.get_icons_directory() / icon_file
        logging.debug(f"Creating icon widget for: {icon_path}")
        btn.setIcon(QtGui.QIcon(str(icon_path)))
        btn.setIconSize(QSize(ICON_SIZE, ICON_SIZE))
        btn.setFixedSize(BUTTON_SIZE, BUTTON_SIZE)
        btn.setCheckable(True)
        btn.setCursor(Qt.CursorShape.PointingHandCursor)  # Show hand cursor on hover
        btn.setStyleSheet(ICON_BUTTON_STYLE)
        
        # Connect button click to icon selection
        btn.clicked.connect(lambda checked, path=icon_path, b=btn, filename=icon_file: 
                          self.select_icon(path, b, filename))
        
        # Add button to container (always add the button)
        container_layout.addWidget(btn, 0, Qt.AlignmentFlag.AlignHCenter)
        
        # Add label below button if display name exists
        if display_name:
            title_label = QtWidgets.QLabel(display_name)
            title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            title_label.setWordWrap(True)
            title_label.setMaximumWidth(LABEL_MAX_WIDTH)
            title_label.setMinimumHeight(LABEL_MIN_HEIGHT)
            title_label.setMinimumWidth(80)  # Ensure minimum width for readability
            title_label.setStyleSheet(LABEL_STYLE)
            container_layout.addWidget(title_label, 0, Qt.AlignmentFlag.AlignHCenter)
        
        # Add container to grid layout with spacing
        layout.addWidget(container, row, col, Qt.AlignmentFlag.AlignCenter)
        if layout.spacing() < 8:
            layout.setSpacing(12)  # Add spacing between icon cards
        self.icon_buttons.append(btn)

        # Record entry for search/filtering
        primary_tag = ""
        secondary_tags = ""
        designer = ""
        icon_geography = ""
        if icon_file in self.icon_metadata:
            md = self.icon_metadata[icon_file]
            primary_tag = md.get("primary_tag", "") or ""
            secondary_tags = md.get("secondary_tags", "") or ""
            designer = md.get("designer", "") or ""
            icon_geography = md.get("icon_geography", "") or ""
        search_text = " ".join(
            (primary_tag, secondary_tags, designer, icon_geography)
        ).strip().lower()
        self.icon_entries.append({
            'button': btn,
            'container': container,
            'icon_file': icon_file,
            'primary_tag': primary_tag,
            'secondary_tags': secondary_tags,
            'search_text': search_text,
        })

    def on_search_text_changed(self, text):
        """
        Filter visible icons based on search text.
        Matches against primary/secondary tags, icon geography, and designer.
        """
        # If icon entries haven't been created yet, nothing to filter
        if not hasattr(self, 'icon_entries') or not self.icon_entries:
            return

        query = (text or "").strip().lower()

        # Empty search -> show everything
        if not query:
            for entry in self.icon_entries:
                entry_container = entry.get('container')
                if entry_container:
                    entry_container.setVisible(True)
            self._schedule_icon_grid_relayout(force=True)
            return

        # Split into tokens so user can type multiple words
        tokens = [t for t in query.split() if t]
        if not tokens:
            for entry in self.icon_entries:
                entry_container = entry.get('container')
                if entry_container:
                    entry_container.setVisible(True)
            self._schedule_icon_grid_relayout(force=True)
            return

        # Apply filter
        for entry in self.icon_entries:
            haystack = entry.get('search_text', '')
            visible = all(token in haystack for token in tokens)
            entry_container = entry.get('container')
            if entry_container:
                entry_container.setVisible(visible)
        self._schedule_icon_grid_relayout(force=True)

    def _svg_search_directories(self):
        """Directories to search for <unique-id>.svg in the cache."""
        dirs = []
        if getattr(self, 'actual_icons_dir', None):
            dirs.append(Path(self.actual_icons_dir))
        if self.data_manager:
            dirs.extend(self.data_manager.get_svg_search_directories())
        seen = set()
        unique = []
        for d in dirs:
            key = d.resolve()
            if key not in seen:
                seen.add(key)
                unique.append(d)
        return unique

    def _find_svg_file(self, png_filename):
        """Find SVG with the same stem as the PNG (e.g. 047678c6.png → 047678c6.svg)."""
        if not png_filename:
            return None
        stem = Path(png_filename).stem
        if not stem or stem.startswith('._'):
            return None
        svg_name = f"{stem}.svg"
        for folder in self._svg_search_directories():
            candidate = folder / svg_name
            if candidate.is_file() and not candidate.name.startswith('._'):
                return candidate
        if self.data_manager:
            for candidate in self.data_manager.cache_dir.rglob(svg_name):
                if '__MACOSX' in candidate.parts or candidate.name.startswith('._'):
                    continue
                return candidate
        return None

    def _update_svg_format_toggle(self):
        """Enable or disable the SVG radio based on the selected icon."""
        if not hasattr(self, 'svgFormatRadio'):
            return
        has_svg = bool(
            self.selected_icon_svg
            and Path(self.selected_icon_svg).is_file()
        )
        self.svgFormatRadio.setEnabled(has_svg)
        if not has_svg and self.use_svg_format:
            self.use_svg_format = False
            if hasattr(self, 'pngFormatRadio'):
                self.pngFormatRadio.setChecked(True)
    
    def select_icon(self, icon_path, button, filename):
        """
        Handle icon selection when a button is clicked.
        
        Args:
            icon_path: Full path to the selected icon (PNG)
            button: The button that was clicked
            filename: The filename of the selected icon
        """
        # Store the selected icon (PNG)
        self.selected_icon = icon_path
        self.selected_icon_png = icon_path
        self.selected_icon_filename = filename
        
        logging.info("Selected icon %s at %s", filename, icon_path)
        self.selected_icon_svg = self._find_svg_file(filename)
        if hasattr(self, 'formatGroup'):
            self.formatGroup.setVisible(True)
        if hasattr(self, 'pngFormatRadio'):
            self.pngFormatRadio.setEnabled(True)
        self._update_svg_format_toggle()
        self.update_selected_icon_format()
        
        # Uncheck all other buttons (single selection)
        for btn in self.icon_buttons:
            if btn is not button:
                btn.setChecked(False)
        
        # Ensure the clicked button is checked
        button.setChecked(True)
        
        # Show metadata panel and update display
        self.metadataPanel.setVisible(True)
        if hasattr(self, "splitter"):
            total = max(self.splitter.width(), 800)
            meta_width = 340
            self.splitter.setSizes([total - meta_width, meta_width])
        self._schedule_icon_grid_relayout()
        self.update_metadata_display(filename, icon_path)
        
    def on_format_changed(self):
        """Handle format radio button change (PNG/SVG)."""
        if hasattr(self, 'svgFormatRadio') and self.svgFormatRadio.isChecked():
            self.use_svg_format = True
        else:
            self.use_svg_format = False
        self.update_selected_icon_format()
        
        # Update the icon preview in metadata panel to show the selected format
        if hasattr(self, 'iconPreviewLabel'):
            preview_pixmap = None
            # If SVG is selected and available, render SVG into a pixmap
            if self.use_svg_format and self.selected_icon_svg and Path(self.selected_icon_svg).exists():
                preview_pixmap = self._render_svg_to_pixmap(
                    self.selected_icon_svg, METADATA_PREVIEW_SIZE
                )
                logging.info(f"Preview updated to SVG: {self.selected_icon_svg}")
            # Fallback to PNG
            if preview_pixmap is None and self.selected_icon_png:
                icon_path_str = str(self.selected_icon_png)
                pixmap = QtGui.QPixmap(icon_path_str)
                if not pixmap.isNull():
                    preview_pixmap = pixmap.scaled(
                        METADATA_PREVIEW_SIZE,
                        METADATA_PREVIEW_SIZE,
                        Qt.AspectRatioMode.KeepAspectRatio,
                        Qt.TransformationMode.SmoothTransformation,
                    )
                    logging.info(f"Preview updated to PNG: {self.selected_icon_png}")
            # Apply pixmap if we have one
            if preview_pixmap is not None:
                self.iconPreviewLabel.setPixmap(preview_pixmap)
    
    def update_selected_icon_format(self):
        """Update selected_icon based on current format selection."""
        if self.use_svg_format and self.selected_icon_svg and self.selected_icon_svg.exists():
            self.selected_icon = self.selected_icon_svg
            logging.info(f"Updated selected_icon to SVG: {self.selected_icon}")
        else:
            self.selected_icon = self.selected_icon_png
            logging.info(f"Updated selected_icon to PNG: {self.selected_icon}")

    def _normalized_svg_markup(self, svg_path):
        """Return SVG text with styles restored and QGIS params resolved."""
        svg_path = Path(svg_path)
        return _normalize_svg_markup(svg_path.read_text(encoding="utf-8"))

    def _svg_stroke_width_mm(self, svg_path, size_mm):
        """
        Stroke width in mm that reproduces the SVG's designed stroke at size_mm.

        QGIS substitutes param(outline-width) with the symbol layer's stroke
        width, which is measured in millimetres. Scale it by the viewBox so
        the map symbol matches the PNG.
        """
        try:
            markup = Path(svg_path).read_text(encoding="utf-8")
            view_box = re.search(r'viewBox\s*=\s*"([^"]+)"', markup)
            design_width = re.search(r"param\(outline-width\)[,\s]+([0-9.]+)", markup)
            if not view_box or not design_width:
                return None
            box_width = float(view_box.group(1).split()[2])
            if box_width <= 0:
                return None
            return float(design_width.group(1)) * size_mm / box_width
        except (OSError, ValueError, IndexError) as err:
            logging.warning(f"Could not derive stroke width for {svg_path}: {err}")
            return None

    def _render_svg_to_pixmap(self, svg_path, target_size=None):
        """
        Render an SVG file to a QPixmap for preview purposes.
        
        Args:
            svg_path: Path to the SVG file
            target_size: Maximum width/height of the preview
        Returns:
            QPixmap or None if rendering fails
        """
        try:
            if target_size is None:
                target_size = METADATA_PREVIEW_SIZE
            markup = self._normalized_svg_markup(svg_path)
            renderer = QSvgRenderer(QByteArray(markup.encode("utf-8")))
            if not renderer.isValid():
                logging.warning(f"QSvgRenderer could not load SVG: {svg_path}")
                return None
            
            # Use the SVG's default size, but constrain to target_size
            default_size = renderer.defaultSize()
            if default_size.width() <= 0 or default_size.height() <= 0:
                default_size = QSize(target_size, target_size)
            
            scale = min(target_size / default_size.width(), target_size / default_size.height())
            width = max(1, int(default_size.width() * scale))
            height = max(1, int(default_size.height() * scale))
            
            pixmap = QtGui.QPixmap(width, height)
            pixmap.fill(Qt.GlobalColor.transparent)
            
            painter = QtGui.QPainter(pixmap)
            renderer.render(painter)
            painter.end()
            return pixmap
        except Exception as e:
            logging.error(f"Error rendering SVG to pixmap: {e}")
            return None

    def update_metadata_display(self, filename, icon_path):
        """
        Update the metadata panel with information for the selected icon.
        
        Args:
            filename: The filename of the selected icon
            icon_path: Full path to the selected icon
        """
        # Update icon preview in the metadata panel
        preview_pixmap = None
        # Prefer SVG preview if SVG is selected and available
        if self.use_svg_format and self.selected_icon_svg and Path(self.selected_icon_svg).exists():
            preview_pixmap = self._render_svg_to_pixmap(
                self.selected_icon_svg, METADATA_PREVIEW_SIZE
            )
        # Fallback to PNG (icon_path argument)
        if preview_pixmap is None and icon_path:
            icon_path_str = str(icon_path)
            pixmap = QtGui.QPixmap(icon_path_str)
            if not pixmap.isNull():
                preview_pixmap = pixmap.scaled(
                    METADATA_PREVIEW_SIZE,
                    METADATA_PREVIEW_SIZE,
                    Qt.AspectRatioMode.KeepAspectRatio,
                    Qt.TransformationMode.SmoothTransformation,
                )
        if preview_pixmap is not None:
            self.iconPreviewLabel.setPixmap(preview_pixmap)
        else:
            self.iconPreviewLabel.setText("Icon preview not available")
        
        self._reset_metadata_label_heights()
        meta = self.icon_metadata.get(filename)
        if meta:
            dash = "-"
            tag = (meta.get("primary_tag") or "").strip()
            self.codeValue.setText(tag or "No category")
            if tag:
                self.codeValue.setStyleSheet(PRIMARY_TAG_VALUE_STYLE)
            else:
                self.codeValue.setStyleSheet(METADATA_VALUE_STYLE)
            self.createdByValue.setText(meta.get("designer") or dash)
            self.createdValue.setText(meta.get("when_created") or dash)
            self.modifiedByValue.setText(meta.get("uploader") or dash)
            self.modifiedValue.setText(meta.get("where_created") or dash)
            self._set_label("whenUploadedValue", meta.get("when_uploaded"))
            self._set_label("secondaryTagsValue", meta.get("secondary_tags"))
            self._set_label("iconGeographyValue", meta.get("icon_geography"))
            self._set_label("iconDescriptionValue", meta.get("icon_description"))
            self._set_label("iconContextValue", meta.get("icon_context"))
            self._set_label("creationContextValue", meta.get("creation_context"))
            notes = (meta.get("notes") or "").strip()
            if not notes:
                notes = (meta.get("metadata_source") or "").strip()
            self._set_label("notesValue", notes or None)
        else:
            self.codeValue.setText("No category")
            self.codeValue.setStyleSheet(METADATA_VALUE_STYLE)
            self.createdByValue.setText(filename)
            self.createdValue.setText("-")
            self.modifiedByValue.setText("-")
            self.modifiedValue.setText("-")
            for attr in (
                "whenUploadedValue",
                "secondaryTagsValue",
                "iconGeographyValue",
                "iconDescriptionValue",
                "iconContextValue",
                "creationContextValue",
                "notesValue",
            ):
                self._set_label(attr, None)

        QTimer.singleShot(0, self._sync_metadata_layout)

    def get_selected_icon_symbol(self):
        """
        Return a QgsMarkerSymbol using the selected icon, or None if nothing is selected.
        
        This method supports both PNG and SVG formats based on user selection.
        
        Returns:
            QgsMarkerSymbol: A marker symbol using the selected icon (PNG or SVG), or None
        """
        if not self.selected_icon:
            return None
            
        try:
            from qgis.core import QgsMarkerSymbol, QgsRasterMarkerSymbolLayer, QgsSvgMarkerSymbolLayer
            from pathlib import Path
            
            icon_path_str = str(self.selected_icon) if self.selected_icon else ""
            icon_path_obj = Path(icon_path_str)
            
            # Check if it's an SVG file
            is_svg = icon_path_obj.suffix.lower() == '.svg' or self.use_svg_format
            
            logging.info(f"=== CREATING SYMBOL ===")
            logging.info(f"Icon path: {icon_path_str}")
            logging.info(f"File extension: {icon_path_obj.suffix}")
            logging.info(f"use_svg_format flag: {self.use_svg_format}")
            logging.info(f"is_svg result: {is_svg}")
            logging.info(f"File exists: {icon_path_obj.exists()}")
            
            # Create a marker symbol
            symbol = QgsMarkerSymbol.createSimple({
                'name': 'circle',  # fallback shape
                'size': '6',
                'color': '0,0,0,0'  # transparent, so only the image shows
            })
            
            if is_svg and icon_path_obj.exists():
                # Pass the original markup. QGIS reads param(outline) /
                # param(outline-width) straight from the file to decide
                # whether stroke colour and width are editable in Symbology.
                logging.info(f"✓ Using SVG format: {icon_path_str}")
                svg_layer = QgsSvgMarkerSymbolLayer(icon_path_str)
                svg_layer.setSize(6)
                stroke_width = self._svg_stroke_width_mm(icon_path_obj, 6)
                if stroke_width is not None:
                    svg_layer.setStrokeWidth(stroke_width)
                symbol.changeSymbolLayer(0, svg_layer)
            else:
                # Use raster marker symbol layer for PNG
                if not icon_path_obj.exists():
                    logging.warning(f"✗ File does not exist: {icon_path_str}")
                logging.info(f"✓ Using PNG format: {icon_path_str}")
                raster_layer = QgsRasterMarkerSymbolLayer(icon_path_str, 6)
                symbol.changeSymbolLayer(0, raster_layer)
            
            return symbol
            
        except ImportError:
            print("QGIS core modules not available")
            return None
        except Exception as e:
            logging.error(f"Error creating symbol: {e}")
            return None

    def clear_selection(self):
        """Clear the current icon selection and hide metadata panel."""
        self.selected_icon = None
        self.selected_icon_png = None
        self.selected_icon_svg = None
        self.selected_icon_filename = None
        self.use_svg_format = False
        
        # Uncheck all buttons
        for btn in self.icon_buttons:
            btn.setChecked(False)
        
        # Hide metadata panel
        self.metadataPanel.setVisible(False)
        if hasattr(self, "splitter"):
            total = max(self.splitter.width(), 1)
            self.splitter.setSizes([total, 0])
        self._schedule_icon_grid_relayout()
